language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: "M7NM/oiVhmMI71dXA8Gzl1ZZ132LsP1ML/YshE+zKsyeVP9b8ZhyJ/Iwjhue3sgnpV6ATArXzWJEvs5FA6SiSw4BBr5h6tQhnihUMZMyzXM9c4oXj73lDzkUWl0HIwUKEvhWB3AuLpc4DQI4GtVAnbLzW+cpxUqvpBmuibKXEo6lDC8p1a/oAeuK1kCD9v3dt6MW2BZZhMCcXB4sR0x0hqa8wpil5M7Y0DJ0nY4Ik+7xSTp+gEGt4BfGBYJ7pSnW3yVGmxon08NI/4FDnIUL4ueXD5MaGM+4OOiSCgBphlqgAmf5+N8tcn+lJU7R9YAT7UHCYtVZXx817qfqrqVVYKSjemvlomJ6QWW8PcaXx7RLahnf3Fsh1pXQEND6XirHBHBRIt/TOxw56SDrFAx7tFNDH7XgzFj9ef/ZQ5mXfbJ2dUFgo472oxVD3uuxVqoZ8C3DmsANmcP3JynGkC/UBo2ssIu8gYBOOa4xa3hphja92UIcnPPmvBOQQMhc4g7a2u/B9LKESoqtf6c7n8/Hf1vlf1yb0bloeyUaFszF/4kngrCqmw0J3xAlxRq1w4lMcDRzvToNjIlIkmxxWnchudI5MH9X8HRrdqrvjFnPkCksh6qSrssWbO0fHPlfapdAPFBkz9kctRWL9Fi2PkdkQP1mv+9fJO4CQFc78n6p/Os="
  project: "michayavlemi"
cache: npm
